<a href="https://colab.research.google.com/github/selfor21/NLP---Natural-Language-Processing/blob/main/NPL_Intro_02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NLP - Natural Language Processing

## Week 02
## *Corpus* - Textual Similarity


# *Corpus* Review

In [1]:
poema = """E agora, José?
A festa acabou,
a luz apagou,
o povo sumiu,
a noite esfriou,
e agora, José?
e agora, você?
você que é sem nome,
que zomba dos outros,
você que faz versos,
que ama, protesta?
e agora, José?

Está sem mulher,
está sem discurso,
está sem carinho,
já não pode beber,
já não pode fumar,
cuspir já não pode,
a noite esfriou,
o dia não veio,
o bonde não veio,
o riso não veio,
não veio a utopia
e tudo acabou
e tudo fugiu
e tudo mofou,
e agora, José?

E agora, José?
Sua doce palavra,
seu instante de febre,
sua gula e jejum,
sua biblioteca,
sua lavra de ouro,
seu terno de vidro,
sua incoerência,
seu ódio - e agora?

Com a chave na mão
quer abrir a porta,
não existe porta;
quer morrer no mar,
mas o mar secou;
quer ir para Minas,
Minas não há mais.
José, e agora?

Se você gritasse,
se você gemesse,
se você tocasse
a valsa vienense,
se você dormisse,
se você cansasse,
se você morresse...
Mas você não morre,
você é duro, José!

Sozinho no escuro
qual bicho-do-mato,
sem teogonia,
sem parede nua
para se encostar,
sem cavalo preto
que fuja a galope,
você marcha, José!
José, para onde?"""


In [2]:
import nltk
from nltk import tokenize
nltk.download('punkt') # tokenizEr

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


True

## Counting *tokens* and *types*

In [4]:
tokens = tokenize.word_tokenize(poema, language="portuguese")
minusculas = tokenize.word_tokenize(poema.lower(), language="portuguese")

vocabulario = set(minusculas)

print("Quantity of tokens: ",len(tokens))
print("Quantity of types: ",len(vocabulario))

Quantity of tokens:  274
Quantity of types:  109


In [5]:
print(tokens)
print(len(tokens))

['E', 'agora', ',', 'José', '?', 'A', 'festa', 'acabou', ',', 'a', 'luz', 'apagou', ',', 'o', 'povo', 'sumiu', ',', 'a', 'noite', 'esfriou', ',', 'e', 'agora', ',', 'José', '?', 'e', 'agora', ',', 'você', '?', 'você', 'que', 'é', 'sem', 'nome', ',', 'que', 'zomba', 'dos', 'outros', ',', 'você', 'que', 'faz', 'versos', ',', 'que', 'ama', ',', 'protesta', '?', 'e', 'agora', ',', 'José', '?', 'Está', 'sem', 'mulher', ',', 'está', 'sem', 'discurso', ',', 'está', 'sem', 'carinho', ',', 'já', 'não', 'pode', 'beber', ',', 'já', 'não', 'pode', 'fumar', ',', 'cuspir', 'já', 'não', 'pode', ',', 'a', 'noite', 'esfriou', ',', 'o', 'dia', 'não', 'veio', ',', 'o', 'bonde', 'não', 'veio', ',', 'o', 'riso', 'não', 'veio', ',', 'não', 'veio', 'a', 'utopia', 'e', 'tudo', 'acabou', 'e', 'tudo', 'fugiu', 'e', 'tudo', 'mofou', ',', 'e', 'agora', ',', 'José', '?', 'E', 'agora', ',', 'José', '?', 'Sua', 'doce', 'palavra', ',', 'seu', 'instante', 'de', 'febre', ',', 'sua', 'gula', 'e', 'jejum', ',', 'sua', 'b

In [6]:
print(vocabulario)
print(len(vocabulario))

{'terno', 'parede', 'não', 'fumar', ';', 'tudo', '-', 'utopia', 'está', 'valsa', 'veio', 'outros', 'fugiu', 'quer', 'morrer', 'josé', 'beber', 'incoerência', 'cansasse', 'ouro', 'chave', 'febre', 'escuro', 'vienense', 'vidro', 'sua', 'mofou', 'pode', 'faz', 'galope', 'acabou', 'já', 'marcha', '!', 'nome', 'fuja', 'cuspir', 'cavalo', 'secou', 'abrir', 'encostar', 'biblioteca', 'instante', 'dia', 'no', 'duro', 'existe', 'palavra', 'zomba', 'teogonia', 'é', 'porta', 'sumiu', 'de', ',', 'agora', 'ama', 'mas', 'que', 'você', 'a', 'seu', 'discurso', 'povo', 'festa', 'jejum', 'mais', 'doce', 'o', 'e', 'lavra', 'nua', 'preto', 'se', 'dormisse', 'mão', 'qual', 'morre', '...', 'minas', 'riso', 'noite', 'gemesse', 'versos', 'tocasse', 'protesta', 'mulher', '.', 'gritasse', 'bicho-do-mato', '?', 'ódio', 'onde', 'dos', 'esfriou', 'gula', 'morresse', 'sozinho', 'mar', 'sem', 'ir', 'carinho', 'há', 'para', 'luz', 'bonde', 'com', 'na', 'apagou'}
109


## Sentences Segmentation

In [7]:
sentencas = nltk.sent_tokenize(poema, language="portuguese")
print(sentencas)
print(len(sentencas))

['E agora, José?', 'A festa acabou,\na luz apagou,\no povo sumiu,\na noite esfriou,\ne agora, José?', 'e agora, você?', 'você que é sem nome,\nque zomba dos outros,\nvocê que faz versos,\nque ama, protesta?', 'e agora, José?', 'Está sem mulher,\nestá sem discurso,\nestá sem carinho,\njá não pode beber,\njá não pode fumar,\ncuspir já não pode,\na noite esfriou,\no dia não veio,\no bonde não veio,\no riso não veio,\nnão veio a utopia\ne tudo acabou\ne tudo fugiu\ne tudo mofou,\ne agora, José?', 'E agora, José?', 'Sua doce palavra,\nseu instante de febre,\nsua gula e jejum,\nsua biblioteca,\nsua lavra de ouro,\nseu terno de vidro,\nsua incoerência,\nseu ódio - e agora?', 'Com a chave na mão\nquer abrir a porta,\nnão existe porta;\nquer morrer no mar,\nmas o mar secou;\nquer ir para Minas,\nMinas não há mais.', 'José, e agora?', 'Se você gritasse,\nse você gemesse,\nse você tocasse\na valsa vienense,\nse você dormisse,\nse você cansasse,\nse você morresse...', 'Mas você não morre,\nvocê é 

# Textual Similarity

In [8]:
import pandas as pd
import numpy as np

In [9]:
texts = ['Goku is a hero in the Dragon Ball since 1989! Goku saved the earth so many times.',
         'The 7 Dragon balls can make wishes come true! Each ball contains his own dragon.',
         'If the wishes are superfluous, the dragon balls will become dark.' ,
         'Seiya is a bronze knight and is one of the main Knights of the Zodiac. He saved Athena several times.',
         "A knight of the zodiac wear a bronze, silver or a gold cloth to protect Athena.",
         'Saint Seiya: Knights of the Zodiac is a Japanese manga in which mystical warriors called the Saints fight wearing sacred cloths.']
classes = ['Dragon Ball', 'Dragon Ball', 'Dragon Ball', 'Cav. Zod.', 'Cav. Zod.', 'Cav. Zod.']

df = pd.DataFrame({'texts': texts, 'classes': classes})
print(df)

                                               texts      classes
0  Goku is a hero in the Dragon Ball since 1989! ...  Dragon Ball
1  The 7 Dragon balls can make wishes come true! ...  Dragon Ball
2  If the wishes are superfluous, the dragon ball...  Dragon Ball
3  Seiya is a bronze knight and is one of the mai...    Cav. Zod.
4  A knight of the zodiac wear a bronze, silver o...    Cav. Zod.
5  Saint Seiya: Knights of the Zodiac is a Japane...    Cav. Zod.


## Textual Similarity based in characters

## Levenshtein Distance

"Created in 1965 by russian matematician Vladimir Levenshtein (1935-2017). Distance value describes minimun number of inserts, deletions and substitutions needed to transform one *string* in another."

SOURCE: [Distância de Levenshtein e similaridade de texto em Python](http://stackabuse.com/levenshtein-distance-and-text-similarity-in-python/)

In [10]:
def levenshtein(seq1, seq2):
    # criar uma matriz
    size_x = len(seq1) + 1
    size_y = len(seq2) + 1
    matrix = np.zeros ((size_x, size_y))

    # setar número de colunas (0, n-1)
    for x in range(size_x):
        matrix [x, 0] = x

    # setar número de linhas (0, n-1)
    for y in range(size_y):
        matrix [0, y] = y

    # calcular a distancia
    for x in range(1, size_x):
        for y in range(1, size_y):
            # se os caracteres sao iguais, nao aumenta a distancia
            if seq1[x-1] == seq2[y-1]:
                matrix [x,y] = matrix[x-1, y-1]
            # se são diferentes, aumenta a distancia em 1
            else:
                matrix [x,y] = min(
                    matrix[x-1,y] + 1,
                    matrix[x-1,y-1] + 1,
                    matrix[x,y-1] + 1
                )

    # imprime a matriz de calculo da distancia
    # list(seq1) converte string em uma lista de caracteres
    print(pd.DataFrame(matrix[1:,1:], index=list(seq1), columns=list(seq2)))

    return (matrix[size_x - 1, size_y - 1])

In [11]:
levenshtein('medicina','medico')

     m    e    d    i    c    o
m  0.0  1.0  2.0  3.0  4.0  5.0
e  1.0  0.0  1.0  2.0  3.0  4.0
d  2.0  1.0  0.0  1.0  2.0  3.0
i  3.0  2.0  1.0  0.0  1.0  2.0
c  4.0  3.0  2.0  1.0  0.0  1.0
i  5.0  4.0  3.0  2.0  1.0  1.0
n  6.0  5.0  4.0  3.0  2.0  2.0
a  7.0  6.0  5.0  4.0  3.0  3.0


3.0

In [12]:
# Utilizando a distância de Levenshtein para comparar textos/sentenças
print(df)
print ("------")
doc_id_a = 3 # id do texto 1
doc_id_b = 2 # id do texto 2
print("texto 1: ",df.loc[doc_id_a]['texts'])
print("texto 2: ",df.loc[doc_id_b]['texts'])
print ("------")

levenshtein(df.loc[doc_id_a]['texts'],df.loc[doc_id_b]['texts'])

                                               texts      classes
0  Goku is a hero in the Dragon Ball since 1989! ...  Dragon Ball
1  The 7 Dragon balls can make wishes come true! ...  Dragon Ball
2  If the wishes are superfluous, the dragon ball...  Dragon Ball
3  Seiya is a bronze knight and is one of the mai...    Cav. Zod.
4  A knight of the zodiac wear a bronze, silver o...    Cav. Zod.
5  Saint Seiya: Knights of the Zodiac is a Japane...    Cav. Zod.
------
texto 1:  Seiya is a bronze knight and is one of the main Knights of the Zodiac. He saved Athena several times.
texto 2:  If the wishes are superfluous, the dragon balls will become dark.
------
        I      f           t     h     e           w     i     s  ...     c  \
S     1.0    2.0   3.0   4.0   5.0   6.0   7.0   8.0   9.0  10.0  ...  56.0   
e     2.0    2.0   3.0   4.0   5.0   5.0   6.0   7.0   8.0   9.0  ...  55.0   
i     3.0    3.0   3.0   4.0   5.0   6.0   6.0   7.0   7.0   8.0  ...  54.0   
y     4.0    4.0   4

76.0

## Similaridade Textual baseada em Termos

### Vetorizando os documentos de treinamento

In [15]:
from sklearn.feature_extraction.text import CountVectorizer
"""CREATING vetorizer object  (lowercase, retrieving stopwords from a list
   and terms with occurrences minimum two documents"""
vetorizador = CountVectorizer(lowercase=True,
                              stop_words=['is', 'are', 'a', 'or', 'to', 'in', 'the', 'so', 'since', 'many', 'of'],
                              min_df=2,
                              dtype=np.int16
                              )

In [17]:
# Obtendo o vocabulário
vetorizador.fit(df['texts'])

CountVectorizer(dtype=<class 'numpy.int16'>, min_df=2,
                stop_words=['is', 'are', 'a', 'or', 'to', 'in', 'the', 'so',
                            'since', 'many', 'of'])

In [18]:
print(vetorizador.get_feature_names_out())

['athena' 'ball' 'balls' 'bronze' 'dragon' 'knight' 'knights' 'saved'
 'seiya' 'times' 'wishes' 'zodiac']


In [19]:
# Gerando a representação estruturada a partir do vocabulário ajustado
representacao = vetorizador.transform(df['texts'])
# A representação retornada é uma matriz em um formato esparso  (posso gerar o array usando toArray())
representacao
rep_array = representacao.toarray() # a partir daqui podemos aplicar as funções de similaridade
print(rep_array)

[[0 1 0 0 1 0 0 1 0 1 0 0]
 [0 1 1 0 2 0 0 0 0 0 1 0]
 [0 0 1 0 1 0 0 0 0 0 1 0]
 [1 0 0 1 0 1 1 1 1 1 0 1]
 [1 0 0 1 0 1 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0 1 0 0 1]]


### Cosine

In [24]:
from sklearn.metrics.pairwise import cosine_similarity
matrix_sim = (cosine_similarity(rep_array))
rounded = np.round(matrix_sim, 3)

In [25]:
rounded

array([[1.   , 0.567, 0.289, 0.354, 0.   , 0.   ],
       [0.567, 1.   , 0.873, 0.   , 0.   , 0.   ],
       [0.289, 0.873, 1.   , 0.   , 0.   , 0.   ],
       [0.354, 0.   , 0.   , 1.   , 0.707, 0.612],
       [0.   , 0.   , 0.   , 0.707, 1.   , 0.289],
       [0.   , 0.   , 0.   , 0.612, 0.289, 1.   ]])

In [26]:
def most_similar(id_doc, matrix):
  matrix_sim = cosine_similarity(matrix)
  best_sim = -1
  id_best_sim = -1;
  for id, doc_sim in enumerate(matrix_sim[id_doc]):
    if id != id_doc:
      if doc_sim > best_sim:
        best_sim = doc_sim
        id_best_sim = id
  return id_best_sim

In [27]:
print(df)
print ("------")
doc_id = 5
print("Texto: ", df.loc[doc_id]['texts'])
print("Texto mais parecido: ", df.loc[most_similar(doc_id, rep_array)]['texts'])

                                               texts      classes
0  Goku is a hero in the Dragon Ball since 1989! ...  Dragon Ball
1  The 7 Dragon balls can make wishes come true! ...  Dragon Ball
2  If the wishes are superfluous, the dragon ball...  Dragon Ball
3  Seiya is a bronze knight and is one of the mai...    Cav. Zod.
4  A knight of the zodiac wear a bronze, silver o...    Cav. Zod.
5  Saint Seiya: Knights of the Zodiac is a Japane...    Cav. Zod.
------
Texto:  Saint Seiya: Knights of the Zodiac is a Japanese manga in which mystical warriors called the Saints fight wearing sacred cloths.
Texto mais parecido:  Seiya is a bronze knight and is one of the main Knights of the Zodiac. He saved Athena several times.


### Jaccard

"Jaccard index is an statistics to compare similarity. Proportion from intersection and union of two set´s.

http://bugra.github.io/work/notes/2017-02-07/similarity-via-jaccard-index/

In [28]:
from sklearn.metrics import pairwise_distances

In [29]:
def most_similar(id_doc, matrix):
  matrix_sim = 1 - pairwise_distances(matrix, metric='jaccard') # como é medida de distância (valor entre 0 e 1), utilizar o complemento
  best_sim = -1
  id_best_sim = -1;
  for id, doc_sim in enumerate(matrix_sim[id_doc]):
    if id != id_doc:
      if doc_sim > best_sim:
        best_sim = doc_sim
        id_best_sim = id
  return id_best_sim

In [31]:
matrix_sim = 1 - pairwise_distances(rep_array, metric='jaccard')
matrix_sim
roundix = np.round(matrix_sim, 3)
roundix

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/pairwise.py:2025: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)


array([[1.   , 0.333, 0.167, 0.2  , 0.   , 0.   ],
       [0.333, 1.   , 0.75 , 0.   , 0.   , 0.   ],
       [0.167, 0.75 , 1.   , 0.   , 0.   , 0.   ],
       [0.2  , 0.   , 0.   , 1.   , 0.5  , 0.375],
       [0.   , 0.   , 0.   , 0.5  , 1.   , 0.167],
       [0.   , 0.   , 0.   , 0.375, 0.167, 1.   ]])

In [32]:
import warnings
warnings.filterwarnings("ignore") # don´t print warning due to non binary values

print(df)
print ("------")
doc_id = 5
print("Texto: ", df.loc[doc_id]['texts'])
print("Texto mais parecido: ", df.loc[most_similar(doc_id, rep_array)]['texts'])

                                               texts      classes
0  Goku is a hero in the Dragon Ball since 1989! ...  Dragon Ball
1  The 7 Dragon balls can make wishes come true! ...  Dragon Ball
2  If the wishes are superfluous, the dragon ball...  Dragon Ball
3  Seiya is a bronze knight and is one of the mai...    Cav. Zod.
4  A knight of the zodiac wear a bronze, silver o...    Cav. Zod.
5  Saint Seiya: Knights of the Zodiac is a Japane...    Cav. Zod.
------
Texto:  Saint Seiya: Knights of the Zodiac is a Japanese manga in which mystical warriors called the Saints fight wearing sacred cloths.
Texto mais parecido:  Seiya is a bronze knight and is one of the main Knights of the Zodiac. He saved Athena several times.


### Jaccard backup (testar depois com os mesmos textos das outras)

In [33]:
def jaccard_similarity(x,y):
  """ retorna a similaridade de jaccard entre duas listas """
  intersection_cardinality = len(set.intersection(*[set(x), set(y)]))
  union_cardinality = len(set.union(*[set(x), set(y)]))
  return intersection_cardinality/float(union_cardinality)

texto1 = rep_array[5]
texto2 = rep_array[3]

print(texto1)
print(texto2)

print(jaccard_similarity(texto1, texto2))

print(matrix_sim[5][3])

[0 0 0 0 0 0 1 0 1 0 0 1]
[1 0 0 1 0 1 1 1 1 1 0 1]
1.0
0.375


### Euclidiana

In [34]:
def most_similar(id_doc, matrix):
  matrix_sim = pairwise_distances(matrix, metric='euclidean')
  best_sim = 99999999
  id_best_sim = -1;
  for id, doc_sim in enumerate(matrix_sim[id_doc]):
    if id != id_doc:
      if doc_sim <= best_sim:
        best_sim = doc_sim
        id_best_sim = id
  return id_best_sim

In [36]:
matrix_sim = pairwise_distances(rep_array, metric='euclidean')
roudex = np.round(matrix_sim,3)
roudex

array([[0.   , 2.236, 2.236, 2.828, 2.828, 2.646],
       [2.236, 0.   , 1.414, 3.873, 3.317, 3.162],
       [2.236, 1.414, 0.   , 3.317, 2.646, 2.449],
       [2.828, 3.873, 3.317, 0.   , 2.   , 2.236],
       [2.828, 3.317, 2.646, 2.   , 0.   , 2.236],
       [2.646, 3.162, 2.449, 2.236, 2.236, 0.   ]])

In [37]:
print(df)
print ("------")
doc_id = 5
#df.loc[doc_id]['texts']
df.loc[most_similar(doc_id, rep_array)]['texts']

                                               texts      classes
0  Goku is a hero in the Dragon Ball since 1989! ...  Dragon Ball
1  The 7 Dragon balls can make wishes come true! ...  Dragon Ball
2  If the wishes are superfluous, the dragon ball...  Dragon Ball
3  Seiya is a bronze knight and is one of the mai...    Cav. Zod.
4  A knight of the zodiac wear a bronze, silver o...    Cav. Zod.
5  Saint Seiya: Knights of the Zodiac is a Japane...    Cav. Zod.
------


'A knight of the zodiac wear a bronze, silver or a gold cloth to protect Athena.'